
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const PUT_TO_STORE_DATA = 'PUT_TO_STORE_DATA';
export const FAILED_PROCESSING_DATA = 'FAILED_PROCESSING_DATA';

export const PUT_PRODUCT_TO_BASKET = 'PUT_PRODUCT_TO_BASKET';
export const DELETE_PRODUCT_FROM_BASKET = 'DELETE_PRODUCT_FROM_BASKET';
export const CHANGE_PRODUCT_IN_BASKET = 'CHANGE_PRODUCT_IN_BASKET';

export const CHECKOUT = 'CHECKOUT';
export const SUBMIT_DATA = 'SUBMIT_DATA';


export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
export const CLEAR_BASKET = 'CLEAR_BASKET';
export const CLEAR_ORDER = 'CLEAR_ORDER';

export const RESET_STATE = 'RESET_STATE';
